MvcTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int Departmanid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }

        public ICollection<Personel> Personels { get; set; }
    }
}

MvcTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTicariOtomasyon.Models.Siniflar;

namespace MvcTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x=> x.Durum == true).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }   

        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }   

        public ActionResult DepartmanGetir(int id)
        {
            var dep = c.Departmans.Find(id);
            return View("DepartmanGetir", dep);
        }

        public ActionResult DepartmanGuncelle(Departman p)
        {
            var dept = c.Departmans.Find(p.Departmanid);
            dept.DepartmanAd = p.DepartmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();
            var dpt = c.Departmans.Where(x => x.Departmanid == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
        }

        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x=> x.Personelid == id).ToList();
            var dp = c.Personels.Where(x => x.Personelid == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            ViewBag.dp = dp;
            return View(degerler);  
        }
    }
}

MvcTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcTicariOtomasyon.Models.Siniflar

@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Detay</h2>

<div class="card mb-4">
    <div class="card-body">
        Departman Adı: <b>@ViewBag.d</b>
    </div>
</div>

<table class="table table-hover">
    <tr>
        <th>Personel ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Personelid</td>
            <td>@item.PersonelAd</td>
            <td>@item.PersonelSoyad</td>
            <td>@item.PersonelGorsel</td>
            <td><a href="/Departman/DepartmanPersonelSatis/@item.Personelid" class="btn btn-default" style="background-color:aquamarine">Satışlar</a></td>
        </tr>
    }
</table>

MvcTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcTicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Departman Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.DepartmanAd)
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
<br />
<button type="submit" class="btn btn-success">Ekle</button>

</form>

MvcTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MvcTicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Güncelleme</h2>
<br />

@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.DepartmanAd)
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Departmanid)
    </div>
    <br />

    <button class="btn btn-warning">Güncelle</button>
}

MvcTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>

@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />


<h2>DepartmanPersonelSatis</h2>
<br />

<div class="card mb-4">
    <div class="card-body">
        Personel Adı: <b>@ViewBag.dp</b>
    </div>
</div>


<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-warning">Yazdır</a></td>
        </tr>
    }
</table>

MvcTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.Departmanid
            </td>
            <td>
                @k.DepartmanAd
            </td>
            <td><a href="/Departman/DepartmanSil/@k.Departmanid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.Departmanid" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@k.Departmanid" class="btn btn-default" style="background-color:burlywood">Detay</a></td>
        </tr>
    }
</table>

<a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>